# Changes here will be overwritten by Copier
_commit: v0.8.2
_src_path: https://github.com/fohte/generic-boilerplate
auto_merge_release_pr: false
description: beatoraja のプレイ履歴をリアルタイム表示する Tauri デスクトップアプリ
is_public: false
project_name: bms-dashtray
release_type: simple
repo_language: en
type: base
use_release_please: true
